name: macro_processor
version: 0.0.14
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Lightweight macro processor with syntax similar to C language.
homepage: https://github.com/mezoni/macro_processor
dependencies:
  parser_error: any
  text: any
dev_dependencies:
  build_tools: any
  unittest: any
